### PR TITLE
nav-update

### PR DESCRIPTION
**Pull request by LucaPetrocchi**
Updated nav to remove "Testimonials" and add links. Fixed Tux image path as well.

### CODE REVIEW

**Comment by valentinoarballo** [comment]
main?

**Review by nazabucciarelliITEC — APPROVED** [review]

**Review by FacundoEsteban-Lemo — COMMENTED** [review]
merging to main??

**Comment by valentinoarballo** [comment]
MAIN?!

**Review by nazabucciarelliITEC — COMMENTED** [review]
bro? really? second year and that's all that you can handle? bro?????? main? gtfo!

**Comment by LucaPetrocchi** [comment]
Pulling to develop now. Will leave current career for Tourism by tomorrow morning.

**Review by FacundoEsteban-Lemo — APPROVED** [review]
Let's goooo!! Tourism gang!!!

**Review by valentinoarballo — APPROVED** [review]
OpenAI will obliterate you

**Pull request merged**
