### PR TITLE
Task 008/mockup inscriptions page

### PR DESCRIPTION
**Pull request by valentinoarballo**
some issues with json fixed, new custom CSS created, progress in programs.html

### CODE REVIEW

**Review by FacundoEsteban-Lemo — APPROVED** [review]
useful!

**Review by FacundoEsteban-Lemo — APPROVED** [review]
hell yeah!

**Review by nazabucciarelliITEC — APPROVED** [review]
Good design, and thanks for correcting the json file.

**Comment by valentinoarballo** [comment]
EPIC

**Review by FacundoEsteban-Lemo — APPROVED** [review]
Awesome!

**Review by LucaPetrocchi — APPROVED** [review]

**Pull request merged**
