### PR TITLE
adding main files and folders

### PR DESCRIPTION
**Pull request by nazabucciarelliITEC**
I've added the main html files and app.py

### CODE REVIEW

**Comment by LucaPetrocchi** [comment]
Tested out, all's working as intended.

**Comment by FacundoEsteban-Lemo** [comment]
please stop asking for money and start working.

**Review by LucaPetrocchi — APPROVED** [review]
All is working fine.

**Review by FacundoEsteban-Lemo — APPROVED** [review]
very good work so far!! keep it up!!!11

**Pull request merged**
